---
spring:
  application.name: sample-boot-scala
  aop.proxy-target-class: true
  messages.basename: messages-validation, messages
  cache.jcache.config: classpath:ehcache.xml
  http.multipart:
    max-file-size: 20MB
    max-request-size: 20MB

banner.location: banner.txt

logging.config: classpath:logback-spring.xml

server:
  port: 8080
  error:
    whitelabel.enabled: false
    path: /api/error

security:
  basic.enabled: false
  user.password: unused


management:
  context-path: /api/management
  security.enabled: false
  health:
    diskspace.enabled: true
    db.enabled: false

extension:
  security:
    auth:
      enabled: false
      admin: false
    cors.enabled: true
  mail.enabled: false
  datafixture.enabled: true

---
spring:
  profiles: production

management.security.enabled: true

extension:
  security:
    auth.enabled: true
    cors.enabled: false
  datafixture.enabled: false

---
spring:
  profiles: admin

server.port: 8081

extension: 
  security.auth.admin: true
